-- GENERATED by build.sh from hook/ and installer/ - do not edit by hand
local M = {}
M.hook = [==[
#!/bin/bash
# BatWiiCera Plaza - presence hook for Batocera
# Version 0.1.5 | Author: yiddifliddo | Licence: MIT
#
# Batocera runs every executable in /userdata/system/scripts/ when a game
# starts or stops, passing:  <gameStart|gameStop> <system> <emulator> <core> <rom>
# This script tells the Plaza server what you are playing so the label above
# your avatar is live. It reads your token from the Plaza profile and the
# server address from the Plaza config, both written by the Plaza client.
#
# Nothing is sent if the Plaza has never been run (no profile, so no token)
# or if "Show my game" is off. Without a config.json the public BatWiiCera
# server is used, the same default the client has built in.

EVENT="$1"; SYSTEM="$2"; ROM="$5"

SAVE_DIR="${PLAZA_SAVE_DIR:-$HOME/.local/share/love/batwiicera-plaza}"
PROFILE="$SAVE_DIR/profile.json"
CONFIG="$SAVE_DIR/config.json"

DEFAULT_HOST="maglev.proxy.rlwy.net"
DEFAULT_PRESENCE_URL="https://batwiicera-production.up.railway.app"

[ -f "$PROFILE" ] || exit 0
command -v curl >/dev/null 2>&1 || exit 0

json_field() { # json_field <file> <key>  (flat string/number/bool values only)
  sed -n "s/.*\"$2\"[[:space:]]*:[[:space:]]*\"\{0,1\}\([^\",}]*\)\"\{0,1\}.*/\1/p" "$1" | head -n1
}

TOKEN="$(json_field "$PROFILE" token)"
SHARE="$(json_field "$PROFILE" share)"
if [ -f "$CONFIG" ]; then
  HOST="$(json_field "$CONFIG" host)"
  PORT="$(json_field "$CONFIG" httpPort)"
  PRESENCE_URL="$(sed -n 's/.*"presenceUrl"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$CONFIG" | head -n1)"
else
  HOST="$DEFAULT_HOST"; PORT=""; PRESENCE_URL="$DEFAULT_PRESENCE_URL"
fi
[ -n "$TOKEN" ] || exit 0
[ "$SHARE" = "false" ] && exit 0
PORT="${PORT:-7778}"
# PaaS hosts (Railway and the like) give one HTTPS URL for the presence side;
# a VPS uses host:port. Either way the endpoint is <base>/presence.
if [ -n "$PRESENCE_URL" ]; then BASE="${PRESENCE_URL%/}"; else [ -n "$HOST" ] || exit 0; BASE="http://$HOST:$PORT"; fi

if [ "$EVENT" = "gameStart" ]; then
  # Game name from the ROM file name: strip extension and bracketed tags.
  NAME="$(basename "$ROM")"
  NAME="${NAME%.*}"
  NAME="$(printf '%s' "$NAME" | sed -e 's/ *([^)]*)//g' -e 's/ *\[[^]]*\]//g' -e 's/_/ /g' -e 's/  */ /g' -e 's/^ *//;s/ *$//')"
  [ -n "$SYSTEM" ] && NAME="$NAME ($SYSTEM)"
  NAME="${NAME:0:40}"
  BODY="$(printf '{"token":"%s","event":"start","game":"%s"}' "$TOKEN" "$(printf '%s' "$NAME" | sed 's/"/\\"/g')")"
elif [ "$EVENT" = "gameStop" ]; then
  BODY="$(printf '{"token":"%s","event":"stop"}' "$TOKEN")"
else
  exit 0
fi

# Fire and forget; never hold up the game launch.
( curl -sL -m 6 -X POST -H 'Content-Type: application/json' --data "$BODY" "$BASE/presence" >/dev/null 2>&1 & ) &
exit 0
]==]
M.esSystems = [==[
<?xml version="1.0"?>
<!--
BatWiiCera Plaza - custom system for Batocera EmulationStation
Version 0.1.5 | Author: yiddifliddo | Licence: MIT

Installed to /userdata/system/configs/emulationstation/es_systems_plaza.cfg
by install-batocera.sh, by the client's own installer, by the Ports script or
by unpacking the theme's full-install zip. The launch command first restores
the executable bit on the presence hook, which is lost when files are copied
in over a Windows network share. Batocera merges this file over its own es_systems.cfg,
adding a "Plaza" system whose single entry launches the Plaza client with the
LOVE engine. The theme shows it as a channel tile using the logo named
"plaza".
-->
<systemList>
  <system>
    <name>plaza</name>
    <fullname>Plaza</fullname>
    <manufacturer>BatWiiCera</manufacturer>
    <release>2026</release>
    <hardware>engine</hardware>
    <path>/userdata/roms/plaza</path>
    <extension>.love .LOVE</extension>
    <command>chmod +x /userdata/system/scripts/batwiicera-plaza-presence.sh 2>/dev/null; python /usr/lib/python3*/site-packages/configgen/emulatorlauncher.py %CONTROLLERSCONFIG% -system love -rom %ROM% -gameinfoxml %GAMEINFOXML% -systemname plaza</command>
    <platform>love</platform>
    <theme>plaza</theme>
    <emulators>
      <emulator name="love">
        <cores>
          <core default="true">love</core>
        </cores>
      </emulator>
    </emulators>
  </system>
</systemList>
]==]
M.logo = [==[
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="400" height="160" viewBox="0 0 400 160">
  <!-- BatWiiCera Plaza channel logo. Original artwork, yiddifliddo, MIT. -->
  <defs>
    <linearGradient id="sky" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#7CCDF8"/>
      <stop offset="1" stop-color="#2E95D8"/>
    </linearGradient>
  </defs>
  <!-- little crowd -->
  <g>
    <circle cx="48" cy="62" r="13" fill="#F6D4BA"/><rect x="34" y="78" width="28" height="30" rx="8" fill="#E2473B"/>
    <circle cx="88" cy="54" r="13" fill="#C58C5C"/><rect x="74" y="70" width="28" height="30" rx="8" fill="#3B8BE2"/>
    <circle cx="128" cy="64" r="13" fill="#EBBF9B"/><rect x="114" y="80" width="28" height="30" rx="8" fill="#3DB34A"/>
    <path d="M35,52 a13,13 0 0 1 26,0 z" fill="#4A2F1B"/>
    <path d="M75,44 a13,13 0 0 1 26,0 z" fill="#2A1B12"/>
    <path d="M115,54 a13,13 0 0 1 26,0 z" fill="#E9C46A"/>
    <circle cx="150" cy="106" r="10" fill="#FFFFFF" stroke="#333" stroke-width="2"/>
    <path d="M150,96 l4,7 l-4,3 l-4,-3 z" fill="#333"/>
  </g>
  <!-- wordmark -->
  <text x="175" y="88" font-family="Arial Rounded MT Bold, Arial, Helvetica, sans-serif" font-weight="bold" font-size="56" fill="url(#sky)">PLAZA</text>
  <text x="177" y="118" font-family="Arial, Helvetica, sans-serif" font-size="18" fill="#6E6E6E">meet other players</text>
</svg>
]==]
M.ports = [==[
#!/bin/bash
# BatWiiCera Plaza - one file for Batocera's Ports list: installs, repairs, launches
# Version 0.1.5 | Author: yiddifliddo | Licence: MIT
#
# Drop this file in share\roms\ports (that is /userdata/roms/ports). It shows
# up under Ports as "Plaza". Nothing has to be typed anywhere:
#
#   first launch   - installs the Plaza channel from the BatWiiCera theme
#                    folder (client, EmulationStation system, presence hook,
#                    channel logo, public server address) and restarts
#                    EmulationStation. The Plaza channel is then on the
#                    console grid.
#   later launches - open the Plaza directly, and quietly repair anything
#                    missing first.
#
# It needs the BatWiiCera theme (0.1.15 or newer) in /userdata/themes, because
# the Plaza client ships inside the theme's _plaza folder.

ROMS=/userdata/roms/plaza
ES_CFG=/userdata/system/configs/emulationstation/es_systems_plaza.cfg
HOOK=/userdata/system/scripts/batwiicera-plaza-presence.sh
LOG=/userdata/system/logs/plaza-ports.log
mkdir -p "$(dirname "$LOG")" 2>/dev/null
exec >>"$LOG" 2>&1
echo "== $(date '+%F %T') Plaza.sh start"

# Newest theme copy that carries a Plaza client (PLAZA_SRC overrides).
find_source() {
  [ -n "$PLAZA_SRC" ] && [ -f "$PLAZA_SRC/dist/BatWiiCera-Plaza.love" ] && { echo "$PLAZA_SRC"; return; }
  for d in $(ls -td /userdata/themes/*/_plaza 2>/dev/null); do
    if [ -f "$d/dist/BatWiiCera-Plaza.love" ] && [ -f "$d/installer/install-batocera.sh" ]; then echo "$d"; return; fi
  done
}

installed() { [ -f "$ROMS/Plaza.love" ] && [ -f "$ES_CFG" ] && [ -f "$HOOK" ]; }

if ! installed; then
  SRC="$(find_source)"
  if [ -z "$SRC" ]; then
    echo "No BatWiiCera theme with a _plaza folder found in /userdata/themes. Install the theme first."
    exit 1
  fi
  echo "Installing the Plaza channel from $SRC"
  bash "$SRC/installer/install-batocera.sh"        # built-in public server; restarts EmulationStation
  exit $?
fi

# Already installed: restore the hook's executable bit (lost when copied in
# over a Windows share), then launch the Plaza like the channel tile does.
chmod +x "$HOOK" 2>/dev/null
LAUNCHER="$(ls /usr/lib/python3*/site-packages/configgen/emulatorlauncher.py 2>/dev/null | head -n1)"
if [ -n "$LAUNCHER" ]; then
  exec python "$LAUNCHER" -system love -rom "$ROMS/Plaza.love" -systemname plaza
elif command -v love >/dev/null 2>&1; then
  exec love "$ROMS/Plaza.love"
else
  echo "Neither emulatorlauncher nor love found; cannot start the Plaza."
  exit 1
fi
]==]
M.gamelist = [==[
<?xml version="1.0"?>
<gameList>
  <game>
    <path>./Plaza.love</path>
    <name>Enter the Plaza</name>
    <desc>Meet everyone running BatWiiCera. Walk around, jump, slap, kick the ball and see what people are playing.</desc>
    <developer>yiddifliddo</developer>
    <genre>Social</genre>
  </game>
</gameList>
]==]
return M
