-- BatWiiCera Plaza - self-install on Batocera (no terminal needed)
-- Version 0.1.5 | Author: yiddifliddo | Licence: MIT
--
-- The client runs with full rights on Batocera, so it can install itself:
-- copy this .love to /userdata/roms/plaza, write the Plaza system definition,
-- write the presence hook (executable), put the one-file installer/launcher
-- in roms/ports, drop the channel logo into any installed BatWiiCera theme,
-- then restart EmulationStation so the channel appears straight away. The files it writes are embedded at build time
-- (src/embedded.lua, generated by build.sh from hook/ and installer/).

local embedded = require("src.embedded")

local M = {}

M.paths = {
  userdata = "/userdata",
  roms = "/userdata/roms/plaza",
  esCfgDir = "/userdata/system/configs/emulationstation",
  scripts = "/userdata/system/scripts",
  ports = "/userdata/roms/ports",
  themes = "/userdata/themes",
}

local function exists(path)
  local f = io.open(path, "r")
  if f then f:close(); return true end
  return false
end

local function dirExists(path)
  local ok = os.execute('[ -d "' .. path .. '" ]')
  return ok == 0 or ok == true
end

local function writeFile(path, data, executable)
  local f, err = io.open(path, "wb")
  if not f then return false, err end
  f:write(data)
  f:close()
  if executable then os.execute('chmod 755 "' .. path .. '"') end
  return true
end

local function copyFile(src, dst)
  local i, err = io.open(src, "rb")
  if not i then return false, err end
  local data = i:read("*a"); i:close()
  return writeFile(dst, data)
end

-- True when running on a Batocera-style system (has /userdata).
function M.isBatocera()
  return dirExists(M.paths.userdata)
end

-- What is already in place.
function M.status()
  return {
    system = exists(M.paths.esCfgDir .. "/es_systems_plaza.cfg"),
    hook = exists(M.paths.scripts .. "/batwiicera-plaza-presence.sh"),
    client = exists(M.paths.roms .. "/Plaza.love"),
  }
end

function M.isInstalled()
  local s = M.status()
  return s.system and s.hook and s.client
end

-- Performs the install. Returns ok, list of messages.
function M.install()
  local log = {}
  local function note(m) log[#log + 1] = m end
  if not M.isBatocera() then return false, { "This is not a Batocera system (no /userdata)." } end

  os.execute('mkdir -p "' .. M.paths.roms .. '" "' .. M.paths.esCfgDir .. '" "' .. M.paths.scripts .. '" "' .. M.paths.ports .. '"')

  -- 1. the client itself
  local src = love.filesystem.getSource()
  local ok, err
  if src and src:match("%.love$") and exists(src) then
    ok, err = copyFile(src, M.paths.roms .. "/Plaza.love")
    note(ok and "Copied the Plaza to roms/plaza" or ("Could not copy the Plaza: " .. tostring(err)))
  else
    ok = exists(M.paths.roms .. "/Plaza.love")
    note(ok and "Plaza already in roms/plaza" or "Running from a folder, not a .love file: copy BatWiiCera-Plaza.love to roms/plaza yourself")
  end
  writeFile(M.paths.roms .. "/gamelist.xml", embedded.gamelist)

  -- 2. the Plaza system for EmulationStation
  ok, err = writeFile(M.paths.esCfgDir .. "/es_systems_plaza.cfg", embedded.esSystems)
  note(ok and "Added the Plaza channel to EmulationStation" or ("Could not write the system file: " .. tostring(err)))

  -- 3. the presence hook (must be executable)
  ok, err = writeFile(M.paths.scripts .. "/batwiicera-plaza-presence.sh", embedded.hook, true)
  note(ok and "Installed the presence hook" or ("Could not write the hook: " .. tostring(err)))

  -- 4. the Ports entry: installs or repairs from the theme folder, or launches
  ok, err = writeFile(M.paths.ports .. "/Plaza.sh", embedded.ports, true)
  note(ok and "Added Plaza to the Ports list" or ("Could not write the Ports script: " .. tostring(err)))

  -- 5. channel logo for installed BatWiiCera theme copies that predate 0.1.11
  local p = io.popen('ls -d ' .. M.paths.themes .. '/BatWiiCera*/_inc/systems/logos 2>/dev/null')
  if p then
    for dir in p:lines() do
      if not exists(dir .. "/plaza.svg") then
        writeFile(dir .. "/plaza.svg", embedded.logo)
        note("Added the channel logo to " .. dir:match("themes/([^/]+)/"))
      end
    end
    p:close()
  end

  local st = M.status()
  local good = st.system and st.hook
  note(good and "Done. EmulationStation restarts in a moment; the Plaza channel will be on the console grid." or "Install incomplete, see above.")
  return good, log
end

-- Restarts EmulationStation a few seconds from now, detached from this
-- process, so the client can quit cleanly first. Batocera supervises
-- EmulationStation and brings it back with the new system list.
function M.restartEmulationStation()
  if not M.isBatocera() then return false end
  local cmd = "sleep 3; batocera-es-swissknife --restart"
  local wrap = "nohup setsid bash -c '" .. cmd .. "' >/dev/null 2>&1 </dev/null &"
  local ok = os.execute("command -v setsid >/dev/null 2>&1")
  if not (ok == 0 or ok == true) then
    wrap = "nohup bash -c '" .. cmd .. "' >/dev/null 2>&1 </dev/null &"
  end
  os.execute(wrap)
  return true
end

-- Removes what install() wrote (keeps the player's profile).
function M.uninstall()
  os.remove(M.paths.esCfgDir .. "/es_systems_plaza.cfg")
  os.remove(M.paths.scripts .. "/batwiicera-plaza-presence.sh")
  os.remove(M.paths.roms .. "/gamelist.xml")
  os.remove(M.paths.roms .. "/Plaza.love")
  os.remove(M.paths.ports .. "/Plaza.sh")
  return true
end

return M
