#!/bin/bash
# BatWiiCera Plaza - build the client package
# Version 0.1.6 | Author: yiddifliddo | Licence: MIT
#
# Produces dist/BatWiiCera-Plaza.love (a zip with main.lua at its root) and
# dist/BatWiiCera-Plaza-server.tar.gz. Run from anywhere.
set -e
HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$HERE/client"
mkdir -p "$HERE/dist"
# Embed the files the client installs on Batocera (single source: hook/ and installer/).
{
  echo '-- GENERATED by build.sh from hook/ and installer/ - do not edit by hand'
  echo 'local M = {}'
  for pair in "hook:$HERE/hook/batwiicera-plaza-presence.sh" "esSystems:$HERE/installer/es_systems_plaza.cfg" "logo:$HERE/installer/plaza.svg" "ports:$HERE/installer/Plaza.sh"; do
    key="${pair%%:*}"; file="${pair#*:}"
    printf 'M.%s = [==[\n' "$key"; cat "$file"; printf ']==]\n'
  done
  printf 'M.gamelist = [==[\n'; cat "$HERE/installer/gamelist.xml"; printf ']==]\n'
  echo 'return M'
} > src/embedded.lua
rm -f "$HERE/dist/BatWiiCera-Plaza.love"
zip -q -r -X "$HERE/dist/BatWiiCera-Plaza.love" main.lua conf.lua src test -x '*.DS_Store'
cd "$HERE"
tar --exclude=node_modules -czf "$HERE/dist/BatWiiCera-Plaza-server.tar.gz" server
echo "built:"
ls -la "$HERE/dist"
