-- GENERATED by build.sh from hook/ and installer/ - do not edit by hand
local M = {}
M.hook = [==[
#!/bin/bash
# BatWiiCera Plaza - presence hook for Batocera
# Version 0.1.3 | Author: Dan Lee | Licence: MIT
#
# Batocera runs every executable in /userdata/system/scripts/ when a game
# starts or stops, passing:  <gameStart|gameStop> <system> <emulator> <core> <rom>
# This script tells the Plaza server what you are playing so the label above
# your avatar is live. It reads your token from the Plaza profile and the
# server address from the Plaza config, both written by the Plaza client.
#
# Nothing is sent if the Plaza has never been run, if "Show my game" is off,
# or if no server is configured.

EVENT="$1"; SYSTEM="$2"; ROM="$5"

SAVE_DIR="${PLAZA_SAVE_DIR:-$HOME/.local/share/love/batwiicera-plaza}"
PROFILE="$SAVE_DIR/profile.json"
CONFIG="$SAVE_DIR/config.json"

[ -f "$PROFILE" ] && [ -f "$CONFIG" ] || exit 0
command -v curl >/dev/null 2>&1 || exit 0

json_field() { # json_field <file> <key>  (flat string/number/bool values only)
  sed -n "s/.*\"$2\"[[:space:]]*:[[:space:]]*\"\{0,1\}\([^\",}]*\)\"\{0,1\}.*/\1/p" "$1" | head -n1
}

TOKEN="$(json_field "$PROFILE" token)"
SHARE="$(json_field "$PROFILE" share)"
HOST="$(json_field "$CONFIG" host)"
PORT="$(json_field "$CONFIG" httpPort)"
PRESENCE_URL="$(sed -n 's/.*"presenceUrl"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$CONFIG" | head -n1)"
[ -n "$TOKEN" ] || exit 0
[ "$SHARE" = "false" ] && exit 0
PORT="${PORT:-7778}"
# PaaS hosts (Railway and the like) give one HTTPS URL for the presence side;
# a VPS uses host:port. Either way the endpoint is <base>/presence.
if [ -n "$PRESENCE_URL" ]; then BASE="${PRESENCE_URL%/}"; else [ -n "$HOST" ] || exit 0; BASE="http://$HOST:$PORT"; fi

if [ "$EVENT" = "gameStart" ]; then
  # Game name from the ROM file name: strip extension and bracketed tags.
  NAME="$(basename "$ROM")"
  NAME="${NAME%.*}"
  NAME="$(printf '%s' "$NAME" | sed -e 's/ *([^)]*)//g' -e 's/ *\[[^]]*\]//g' -e 's/_/ /g' -e 's/  */ /g' -e 's/^ *//;s/ *$//')"
  [ -n "$SYSTEM" ] && NAME="$NAME ($SYSTEM)"
  NAME="${NAME:0:40}"
  BODY="$(printf '{"token":"%s","event":"start","game":"%s"}' "$TOKEN" "$(printf '%s' "$NAME" | sed 's/"/\\"/g')")"
elif [ "$EVENT" = "gameStop" ]; then
  BODY="$(printf '{"token":"%s","event":"stop"}' "$TOKEN")"
else
  exit 0
fi

# Fire and forget; never hold up the game launch.
( curl -sL -m 6 -X POST -H 'Content-Type: application/json' --data "$BODY" "$BASE/presence" >/dev/null 2>&1 & ) &
exit 0
]==]
M.esSystems = [==[
<?xml version="1.0"?>
<!--
BatWiiCera Plaza - custom system for Batocera EmulationStation
Version 0.1.3 | Author: Dan Lee | Licence: MIT

Installed to /userdata/system/configs/emulationstation/es_systems_plaza.cfg
by install-batocera.sh. Batocera merges this file over its own es_systems.cfg,
adding a "Plaza" system whose single entry launches the Plaza client with the
LOVE engine. The theme shows it as a channel tile using the logo named
"plaza".
-->
<systemList>
  <system>
    <name>plaza</name>
    <fullname>Plaza</fullname>
    <manufacturer>BatWiiCera</manufacturer>
    <release>2026</release>
    <hardware>engine</hardware>
    <path>/userdata/roms/plaza</path>
    <extension>.love .LOVE</extension>
    <command>python /usr/lib/python3*/site-packages/configgen/emulatorlauncher.py %CONTROLLERSCONFIG% -system love -rom %ROM% -gameinfoxml %GAMEINFOXML% -systemname plaza</command>
    <platform>love</platform>
    <theme>plaza</theme>
    <emulators>
      <emulator name="love">
        <cores>
          <core default="true">love</core>
        </cores>
      </emulator>
    </emulators>
  </system>
</systemList>
]==]
M.logo = [==[
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="400" height="160" viewBox="0 0 400 160">
  <!-- BatWiiCera Plaza channel logo. Original artwork, Dan Lee, MIT. -->
  <defs>
    <linearGradient id="sky" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#7CCDF8"/>
      <stop offset="1" stop-color="#2E95D8"/>
    </linearGradient>
  </defs>
  <!-- little crowd -->
  <g>
    <circle cx="48" cy="62" r="13" fill="#F6D4BA"/><rect x="34" y="78" width="28" height="30" rx="8" fill="#E2473B"/>
    <circle cx="88" cy="54" r="13" fill="#C58C5C"/><rect x="74" y="70" width="28" height="30" rx="8" fill="#3B8BE2"/>
    <circle cx="128" cy="64" r="13" fill="#EBBF9B"/><rect x="114" y="80" width="28" height="30" rx="8" fill="#3DB34A"/>
    <path d="M35,52 a13,13 0 0 1 26,0 z" fill="#4A2F1B"/>
    <path d="M75,44 a13,13 0 0 1 26,0 z" fill="#2A1B12"/>
    <path d="M115,54 a13,13 0 0 1 26,0 z" fill="#E9C46A"/>
    <circle cx="150" cy="106" r="10" fill="#FFFFFF" stroke="#333" stroke-width="2"/>
    <path d="M150,96 l4,7 l-4,3 l-4,-3 z" fill="#333"/>
  </g>
  <!-- wordmark -->
  <text x="175" y="88" font-family="Arial Rounded MT Bold, Arial, Helvetica, sans-serif" font-weight="bold" font-size="56" fill="url(#sky)">PLAZA</text>
  <text x="177" y="118" font-family="Arial, Helvetica, sans-serif" font-size="18" fill="#6E6E6E">meet other players</text>
</svg>
]==]
M.gamelist = [==[
<?xml version="1.0"?>
<gameList>
  <game>
    <path>./Plaza.love</path>
    <name>Enter the Plaza</name>
    <desc>Meet everyone running BatWiiCera. Walk around, jump, slap, kick the ball and see what people are playing.</desc>
    <developer>Dan Lee</developer>
    <genre>Social</genre>
  </game>
</gameList>
]==]
return M
